Flow-Launcher/Flow.Launcher.PluginsManifest

- README.md
Add details in readme
@Flow-Launcher/team
> add explanation to readme

- plugins.json
Should enhanced this with #4...
> Update Window Walker

- README.md
- plugins.json
Add Currency Converter (Flow.Launcher.Plugin.Currency) details to plugin.json for consideration to be added to the Flow Plugin Manager.
Update PluginManifest README.md to correct a few minor errors.
> Currency Converter plugin submission

- plugins.json
from https://github.com/jjw24/WoxDictionary to https://github.com/harrynull/Flow.Launcher.Dictionary
> Update After Transfer WoxDictionary

- plugins.json
Could you check if I packed the binaries correctly? Thanks.
> Update Dictionary to v2.2.1

- plugins.json
> Update Runner plugin

- .github/workflows/updater.yaml
- plugins.json
using actions-js/push@master ran into branch protection issue which is unable to bypass, tried several suggestions. Changing to stefanzweifel/git-auto-commit-action@v4 worked. 
Let's use this one.
> Fix auto updater permission

- updateChecker.py
fix the issue that e-tag will only be updated when an update has been found
> fix etag not being update if version is the same

- plugins.json
- add Todoist
- remove ActionKeyword property on a couple plugins, not needed
> Add Todoist

- plugins.json
Wox.Plugin.Todos port to Flow Launcher
> Wox.Plugin.Todos port to Flow Launcher

- plugins.json
DirectTranslate port to Flow Launcher
> DirectTranslate port to Flow Launcher

- plugins.json
Ported from [Wox.Plugin.Github](https://github.com/JohnTheGr8/Wox.Plugin.Github)
> Add Github plugin

- plugins.json
I hope everything's okay - first time creating a PR 😅
> added isPrime plugin to plugins.json

- plugins.json
SpotifyPremium has moved from the fork to its own repo and continued to be maintained by @fow5040
> update spotifypremium repo details

- plugins.json
Context: https://github.com/Flow-Launcher/Flow.Launcher/discussions/512#discussioncomment-961575
> feat: add Fancy Emoji Python plugin (Wox port)

- .github/workflows/updater.yaml
- README.md
https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/actions/workflows/updater.yaml
Hourly update upstream is too frequent.
Let us change to a daily update.
> CI: hourly update -> every 3h update

- plugins.json
> feat: add a new plugin could show system time

- ci/src/updater.py
Closed #60.
This is the most easier and quicker way.
We would refactor updater.py later, not too long.
> BUG: use `dict.get` replace index

- .github/workflows/validator.yaml
https://github.com/fkirc/skip-duplicate-actions
> Use Skip action instead of path skip

- ci/src/updater.py
close https://github.com/Flow-Launcher/Flow.Launcher/issues/578
> remove v in update checker

- plugins.json
New plugin submission - General weights and measures converter.
> GenConvert plugin submission

- plugins.json
Home Assistant plugin for Flow Launcher
> Add HA-Commander plugin

- plugins.json
Plugin to search materialdesginicons.com icons
> Add Search-MDI plugin

- plugins.json
Flow Launcher plugin to search your Plex Media Server
> Add plugin plexy

- plugins.json
Port QuickUninstaller from https://github.com/h0gan1ee/Wox.Plugin.QuickUninstaller
> port QuickUninstaller

- plugins.json
Plugin to search nexusmods.com for mods
> Add nexusmods search plugin

- plugins.json
Update Color plugin info from 2.0.0 release
> Update Color plugin info from 2.0.0 release

- plugins.json
Adds a plugin to control Windows 10/11 services
> Add windows-services plugin

- ci/src/_utils.py
- ci/src/validator.py
With the plugin store coming soon we should make sure we are not accidently pasting in a file path in the manifest.
> Test IcoPath's are valid formatted URL's

- .github/workflows/python-passed.yml
Use the same git commit function as other workflows.
> Use commit action

- plugins.json
> Add Tenor Flow

- .github/workflows/python-passed.yml
- plugins.json
fix failing plugin tester update
- tested on a protected branch, push works when using the checkout action
> fix plugin tester ci

- .github/workflows/test-python.yml
Need to specify file is run with Python
> Use python exe

- ci/src/test-python.py
> Pass on non python #2

- plugins.json
Add Hello World Node.js example plugin project
> Add Hello World Node.js example plugin project

- plugins.json
Easily search Emoji with bright, detailed preview imagery.
> Add Emoji+ to manifest

- plugins.json
> add Hello World Python plugin

- plugins.json
Adds a plugin that launches your Epic Games Library.
> Add Epic launcher to manifest

- plugins.json
> Add obsidian plugin

- plugins.json
Adds a plugin to browse reddit
> Add reddit plugin

- plugins.json
Adds a plugin to interact with Playnite
> Add Playnite Plugin

- ci/src/discord.py
- ci/src/updater.py
Use the updated tag in output fields
> Use latest version tag

- ci/src/_utils.py
- ci/src/discord.py
- ci/src/updater.py
Improved webhook embed's to look much nicer.
> Reformat webhook

- plugins.json
Plugin that allows you to search your browser history
> Add Browser history plugin

- plugins.json
This PR adds a new plugin that can encode or decode a given string using base64 encoding:
> Add Base64 plugin

- plugins.json
Adds a plugin to quickly change your Wallpaper Engine profile.
> Add Wallpaper Engine Profile Selector plugin

- plugins.json
> Submit Flow Raindrop plugin

- plugins.json
Hi
This is a simple WordReference translation plugin written with JavaScript.
Here is the repo: https://github.com/LeoDupont/Flow.Launcher.Plugin.WordReference
Suggestions welcome!
> Add WordReference plugin

- plugins.json
A plugin for computing the difference between two dates.
Repo: https://github.com/LeoDupont/Flow.Launcher.Plugin.DateDiff
> Add DateDiff plugin

- plugins.json
Fix https://github.com/Flow-Launcher/Flow.Launcher/issues/1302
> Search npm update 1.0.2

- plugins.json
* Added a CyberChef plugin
* Update plugins.json
[Cyberchef](https://github.com/gchq/CyberChef) is a web-based, feature-rich coding suite framework. My plugin allows users to quickly send queries to a custom built CyberChef page efficiently.
> Added a CyberChef plugin

- plugins.json
added new plugin for just getting 1 public and 1 real private IP
> Added my new IP plugin

- .gitignore
- ci/src/_utils.py
- ci/src/update-tested.py
- ci/src/updater.py
Ci will now add a `LatestReleaseDate` field to each plugin if the field is not present or a new release is detected.
In addition when a push to the main branch happens a `DateAdded` field is appended to a plugin's info.
> Add DateAdded & LatestReleaseDate fields

- plugins.json
将插件名修改为Translation Tool
图标地址修改为 https://cdn.jsdelivr.net/gh/qjcXu/Flow.Launcher.Translation/src/assets/images/app.png
> update: 修改了图标的地址和插件名

- plugins.json
Generate discord timestamps using the flow launcher
> Add Discord Timestamps Plugin

- plugins.json
I have created a plugin to search projects in JetBrains IDE.
It should work with all IDEs as long as they are installed from Toolbox.
https://github.com/kenty02/Flow.Launcher.Plugin.JetBrainsIDEProjects
> Add JetBrainsIDEProjects plugin

- ci/src/_utils.py
Add JavaScript & TypeScript languages
> Add JavaScript & TypeScript languages

- plugins.json
Update Hello World Node.js plugin language reference
> Update Hello World Node.js plugin language reference

- plugins.json
Update Cider plugin's language
> Update Cider plugin's language

- plugins.json
I've created a plugin that allows the user to make use of the ChatGPT gpt-3.5 and gpt-4 API's from FlowLauncher.
Looking forward to your review!
> Add ChatGPT plugin

- plugins.json
DeepL plugin to quickly translate with FlowLauncher.
> DeepFlow - plugin.json added

- plugins.json
Wrote a plugin to interface with [Toggl Track](https://toggl.com/).
Cheers for the amazing launcher, I've switched over after using PowerToys Run for a fair while and have been very pleased with the configurability, performance, and developer support.
Repository link: https://github.com/JamesNZL/flow-toggl-plugin
Let me know if you need anything else, cheers again!
> chore: :wrench: add `JamesNZL/flow-toggl-plugin`

- plugins.json
WinsFlow 
Plugin for controlling your open windows
- you can minimize all
- you can maximize all
- you can close all
> Add WinsFlow Plugin

- plugins.json
Plugin for controlling your Sound Volume
> Add VolumeFlow

- plugins.json
[Repository](https://github.com/Odotocodot/VisualStudio4Flow)
Example Pic
> Add Visual Studio Plugin

- plugins.json
Hello!
As was written here: https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/issues/272
I feel free to submit a pull request to update the plugin version manually 😊.
> Update plugin version

- .github/workflows/updater.yaml
- ci/src/updater.py
- Use token for updater's request calls
- Use automatic token authentication
Close #272
Close #267
> Fix null issue in auto updater

- .github/workflows/updater.yaml
Enable the auto updater to run
> Enable schedule

- plugins.json
A plugin for [Flow Launcher](https://github.com/Flow-Launcher/Flow.Launcher) to search your [ryot](https://github.com/IgnisDa/ryot) tracker.
> Add Ryot plugin

- plugins.json
> Fix plugin fields

- plugins.json
Add new plugin for display the IP and MAC address and device name.
> Add plugin to display IP, MAC address and device name

- plugins.json
This PR removes the CyberChef plugin that is no longer available.
> Remove CyberChef plugin

- plugins.json
https://github.com/GoodbyeNJN/Flow.Launcher.Plugin.OneTimePassword
lib list:
- Flow.Launcher.Plugin@4.1.1
- Otp.NET@1.3.0
> Add new plugin One-time Password

- plugins.json
Fix CI link checker failure- icon file moved.
> Fix CI link checker failure

- plugins.json
A URL shortening plugin for [Flow Launcher](https://flowlauncher.com/) to quickly shorten any URL using cleanuri.com API.
> Add new plugin "URL Shortener"

- plugins.json
- A plugin for Find Unicode characters by their names.
- Discussion: https://github.com/Flow-Launcher/Flow.Launcher/discussions/2438
> Add plugin "Unicode Finder"

- plugins.json
Remove Google Calendar plugins
Close #322
> Remove Google Calendar plugin

- plugins.json
Repository Link: [Flow Launcher Prayer Times Plugin](https://github.com/AminSallah/Flow.Launcher.Plugin.Azan)
Let me know if you need anything else.
> New Plugin To get prayer times

- plugins.json
> Adds new plugin - Astro 

- plugins.json
Hi,
This adds a FileZilla plugin.
Regards
> Add plugin "FileZilla"

- plugins.json
A new plugin to search Stardew Valley Wiki.
> Add StardewValleyWiki

- ci/src/updater.py
Remove requests module import. From #319
> Fix auto update workflow fail

- ci/src/discord.py
Fix auto update fail with missing requests package
> Fix auto update fail with missing requests package

- plugins/MyAnimeList-7463e642-7ab5-4df5-b537-56eefcc53e74
Search MyAnimeList within Flow Launcher!
> Add MyAnimeList plugin

- README.md
Update plugins submission steps in README.md
> Update plugins submission steps in README.md

- plugins/QuickLook-e6a13bf1-5op9-2b96-a7fd-130b7vdt3d14.json
> Add QuickLook plugin

- plugins/Open Window Search-0A3D1C9663EB49308749EC0FED268729.json
Quickly switch to an open window.
**Features**
- Quickly search and switch between open windows
- Displays window titles and application names in search results
- Extracts and caches window icons for a visually rich experience
- Supports minimized and maximized windows
> Added Open Window Search Plugin

- plugins/PowerToys-0930723F-73EA-488A-BEE9-8B8D4845B2F1.json
Plugin to run PowerToys utilities from Flow
> New Plugin: PowerToys

- plugins/Emoji Finder-d50362aa29f04cd59032bb44a5d5f7e5.json
A new plugin to easily find emojis by keyword and copy them in the clipboard.
> New plugin: Emoji finder

- plugins/HDRezka Finder-9E3D73EA-6618-40B4-AA2A-60F6F60CDD14.json
This plugin is designed to get faster access to the site HDRezka.me, it contains movies / series, is designed for Russian-speaking users.
> New Plugin: HDRezka Finder

- plugins/Http Status Codes-20CA96840A77452B92D83FB3DD01927C.json
https://github.com/tho-myr/Flow.Launcher.Plugin.Http_Status_Codes
> New Plugin: Http Status Codes

- plugins/Firefox Keyword Bookmarks-bb3ca236-f416-46d5-b88b-597748c33dce.json
> New Plugin: Firefox Keyword Bookmarks

- plugins/Firefox Keyword Bookmarks-bb3ca236-f416-46d5-b88b-597748c33dce.json
Fix incorrect plugin source code url causing CI to fail
> Fix incorrect plugin source code url

- plugins/FlowTamer-2D0AFF97E5A445E3BEDD1081B811075A.json
https://github.com/NoPlagiarism/FlowTamer
> Add FlowTamer

- plugins/Nightlight-95af3946-2bfe-49af-a9b6-edffa42ef1d5.json
- Toggle Windows `nightlight` with `ni` 
- Set the temperature specifically with `ni <1500-6500>`
I hope others find it as useful as i do
> Adding `Nightlight` control plugin.

- plugins/Google Search Plus-4579F00804F94B54B23CF207856E495F.json
Re-add after fix. Following on from #264
> Re-add Google Search plugin

- plugins/Remind Me-522FAF05-36F4-4504-BFF6-5D8F8F4396D5.json
This is a plugin for setting simple reminders.
When it reaches the time set for a reminder, it'll notify the user about it either via a Windows notification or via an always-on-top window (configurable in settings).
https://github.com/Yusyuriv/Flow.Launcher.Plugin.RemindMe
> Add Remind Me plugin

- plugins/QrCodeGenerator-340E73A8A8C148A28082C90207E097B3.json
A plugin for generator QR code and parse QR code file  by csharp.
> Add QR code generator plugin

- plugins/Snippets-4FD15DF08F7146B3AC36AB5F143D8058.json
A simple Snippets  plugin by csharp.
> Add simple Snippets plugin

- plugins/Tenor-22a114b1-aa5f-4bca-8763-03d58bc4029b.json
This adds a Tenor plugin to search GIFs and copy the animate GIF to your clipboard to paste anywhere
> Add Tenor Plugin

- plugins/Gitmoji Plus-218DAC752A2E468AB3781AFAEB481CBF.json
https://github.com/tho-myr/Flow.Launcher.Plugin.Gitmoji_Plus
the original [gitmoji plugin](https://github.com/Galedrim/Flow.Launcher.Plugin.Gitmoji) written in python was lacking a few features, gitmojis and was quite slow for me so i migrated it to csharp for running natively with flow launcher and added the missing gitmojis and some features ^-^ 
changelog for v1.0.0:
🎉 initial plugin release for flow launcher
🏗️ migrated original gitmoji plugin to c#
✨ added missing gitmojis
✨ added copying to clipboard for gitmoji code, description and example
✨ added search functionality for gitmoji code
> New Plugin: Gitmoji Plus 😜

- plugins/Mock-251B44B4162E470B9167A2954DAEBC6E.json
Generate mocking case and memes (⬭ω⬭)
https://github.com/tho-myr/Flow.Launcher.Plugin.Mock
> New Plugin: Mock 🥸

- plugins/Scoop-D8A705AD7AB849ACB581FF46D3B59816.json
Source: https://github.com/xavialyra/Flow.Launcher.Plugin.Scoop
Preview: https://github.com/user-attachments/assets/d3583a01-03a3-4a38-afe4-3d55ba142cf0
> New plugin: Scoop

- plugins/Change Case-44948971-21bf-401a-bb4f-c8b61d4bc429.json
Plugin for change the case of a string
> New Plugin: Change Case

- plugins/Window Manager-d13e69b5-048a-4dce-a950-cbdd5f61f3be.json
Since I have just set this repository to public, we need to wait for a while to make `IcoPath` able to work.
> Add Window Manager plugin

- README.md
Add example for properties & Add helper string
> Add example for properties & Add helper string

- plugins/SteamFlow-A7F3C4E16B8D4B5AB2D7139EEC8FA0B4.json
search Steam store and launch games
> Add plugin: SteamFlow

- plugins/MDict-ba3e8f71-e464-497d-9fa9-515bee26b1d0.json
> Add MDict plugin

- plugins/Insert-b8fda924-12e9-43cf-a35f-0d7aba08ad06.json
A plugin that allows users to replace placeholders in the template string
> Add new plugin: Insert 
