README.md

add link to the current list of available plugins in flow docs, which is generated from the plugins.json here

link to plugin directory in docs

---

.github/workflows/validator.yaml

[validator](https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/blob/main/tests.py) is running only for [plugins.json](https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/blob/main/plugins.json).
But we do other things, this ci would also run. That's unnecessary.

CI: check running when plugins.json get changed

---

.github/workflows/validator.yaml

why there have the same two checks(py3.7, py3.8)?
I consider this has from a test view.
In other projects, I have to handle very thin different version style changes.
Back to this, this project doesn't need to think more about that.
From the function to check pr is fine.

CLN: remove duplicate checking

---

ci/envs/requirements-test-python.txt
ci/src/test-python.py
plugins.json

* Cleans up code
* Doc strings and type hints
* Verify JSON output
* Check and fail on multiple Plugin submission
* Setup faux Flow Launcher structure
* Prioritize `UrlDownload` field for release testing (Fallback to github release if available)
* Support Flox
* Parse `SettingsTemplate.yaml` and send default values to Plugin

Python Plugin Testing upgrade

---

ci/src/test-python.py

This should fix non-Python plugins from causing the test to fail.

Detect and pass on non-Python detection

---

ci/src/test-python.py

This will fix the test from skipping/passing if it detects a non-Python plugin any where in the manifest

Break loop on first detected Python plugin at bottom of dict

---

plugins.json

This fixes missing etag issue, which uses UrlSourceCode

Re-point TimeStamp's url to fork

---

plugins.json

Adds a plugin to view your Github notifications:

Add Github notifications plugin

---

.github/workflows/updater.yaml
ci/src/_utils.py
ci/src/discord.py
ci/src/updater.py

Updater will send a discord webhook to Discord when a plugin's version is changed.
Just need to provide a webhook in repo's secrets named: `DISCORD_WEBHOOK`.

Send discord webhook on plugin updates

---

plugins.json

Simple Github plugin that simplifies accessing repos.

Add Github Quick launcher Plugin

---

plugins.json

Adds a plugin to search twitch.tv emotes as suggested here: https://github.com/Flow-Launcher/Flow.Launcher/discussions/1001

Add plugin to manifest

---

plugins.json

A plugin to utilize [DuckDuckGo's bangs](https://duckduckgo.com/bang) to launch searches on thousands of websites. Port of [Wox.Plugin.Bang](https://github.com/JohnTheGr8/Wox.Plugin.Bang)

Add DuckDuckGo !bang plugin

---

plugins.json

Save notes from anywhere directly into Workflowy.
https://github.com/brunolm/workflowy-wf
https://www.linkedin.com/posts/brunolm_httpslnkdineee2dstp-flow-launcher-plugin-activity-6924539879074770944-N6qB

Add workflowy plugin

---

plugins.json

This PR updates the AWS Toolkit plugin's icon path to be consistent with the format many other Flow Launcher plugins use.

Update AWS Toolkit icon path

---

plugins.json

The motivation for creating this plugin is to provide peace of mind by erasing passwords manually copied from the password manager on the clipboard in as few steps as possible.
Improving existing clipboard plugins requires additional arguments and it is cumbersome to type.
More info: https://github.com/PikkamanV/Flow.Launcher.Plugin.PoiPoiClipboard
Note: "Poi" or "poi-suru" means "to throw away" in Japanese. I first tried to name this plugin "Clipboard Eraser" or "Clipboard Cleaner," but apps with the same name already existed.

Add Poi Poi Clipboard Plugin

---

ci/src/updater.py

If a plugin causes and error it crashes the entire update script.
With this PR the plugin will be skipped and a traceback will be printed.

Catch and skip plugins with errors

---

plugins.json

Adds a plugin to launch Minecraft instances using MultiMC, PolyMC, and PrismLauncher.

Add MC Multi Plugin

---

plugins.json

I developed a new clipboard plugin based on the previous clipboard history plugin, but it's nearly a fresh one.
Repo: https://github.com/rainyl/Flow.Launcher.Plugin.ClipboardR

[new plugin] ClipboardR v0.1.4

---

plugins.json

A plugin for calculating the expected number of trials before an event occurs given a probability (or odds) and confidence level.

Added WhenToExpect

---

ci/src/updater.py

Related to #233
During plugin version update, remove any unused ETags after plugins have been removed from the manifest.

Remove unused etags

---

plugins.json

No longer able to look into this issue due to higher priorities. Temporarily removing this plugin from the store.
From https://github.com/jjw24/Wox.Plugin.GoogleSearch/issues/5

Remove GoogleSearch plugin as it is no longer working

---

plugins.json

Steam Search is no longer considered a "Python" plugin.

Update Steam Search language field

---

.github/workflows/test-python.yml

Change the default Python version for PR plugin test, from 3.8 to 3.11

Change the default Python version for PR plugin test

---

ci/src/_utils.py

fix the following bug
```
Error when processing plugin Youtube Downloader:
invalid literal for int() with base 10: '0-beta' Traceback (most recent call last):
File "/home/runner/work/Flow.Launcher.PluginsManifest/Flow.Launcher.PluginsManifest/./ci/src/updater.py", line 43, in batch_github_plugin_info
send_notification(info, clean(
File "/home/runner/work/Flow.Launcher.PluginsManifest/Flow.Launcher.PluginsManifest/./ci/src/updater.py", line 76, in send_notification
if version_tuple(info[version]) != version_tuple(latest_ver):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/runner/work/Flow.Launcher.PluginsManifest/Flow.Launcher.PluginsManifest/ci/src/_utils.py", line 66, in version_tuple
return tuple(map(int, (version.split("."))))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal …
```

remove integer conversion in version tuple

---

plugins.json

Adds KeePass2Flow, a new plugin that allows connecting to a KeePass2 database using the KeePassRPC plugin.

Add KeePass2Flow

---

.github/workflows/python-passed.yml
plugins/AnyVideo Downloader-70CED0AC-3D9D-4255-AD0B-D9A37862E879.json
plugins/Bitwarden-5A8EBCEB7F6940E5B628BE122A87B560.json
plugins/Git Easy-AA9EA7B6AB4A4822858BC38FF6344248.json
plugins/ShikiFlow-b34023f6440d11ef94540242ac120002.json

Fix 'Update tested plugins' workflow fail due to using unsupported Python version 3.7

Fix 'Update tested plugins' workflow fail

---

ci/src/merge-manifest.py

Disclaimer: I haven't tested this locally, but the change was so tiny, figured I should propose it as-is.
I noticed that the diffs on plugins.json are unreadable because the ordering of plugins changes every time.
As a plugin author, it would be nice to "git blame" the version number of my plugins to see when they were updated automatically by the script.  By ensuring the plugins.json always emit in the same order, we clean up the diffs.
---
Example:
Before, HelloWorldNodeJS is on line 2768.  After it's on line 2.
https://github.com/Flow-Launcher/Flow.Launcher.PluginsManifest/commit/7e5550fbc32dce182447d62cbd26622f607ea549#diff-18d7f9b905f83805c42db6d239a7fb0207d4b32193202eb13ba077caed424c3cR395

Stable emit of plugins.json, so diffs are more readable

---

plugins/Flow Load Notification-5f48576d-efe7-4562-a4ed-fe64455f1ac1.json

Basically just adds a notification that gets shown when the plugin's initialize method is called

New Plugin Flow Load Notification

---

plugins/rtfm-bd4aff8b-108f-4ce9-affb-57c736648fe7.json

made a typo in my rtfm plugin's author field
`ciibere` -> `cibere`

fix typo in rtfm plugin's author

---

plugins/Crates.io-DBBBC4D4C38147A7B0570A473CFA9521.json

This plugin allows users to search crates from crates.io:
* Users can search and open the page of a crate by selecting the result.
* Users can see information about the crate in the context menu, including the GitHub repository, downloads, latest stable version, and latest version.
Project Repository: https://github.com/ahmetoozcan/Flow.Launcher.Plugin.Crates
I mistakenly pushed my commit to plugin_api_v2 in my first pull request and closed it, sorry for the inconvenience

Add Crates.io plugin

---

.github/workflows/python-passed.yml
ci/envs/requirements-update-tested.txt
ci/src/_utils.py
ci/src/discord.py
ci/src/update-tested.py
ci/src/updater.py

Based on #420 
This PR adds a notification that gets triggered in the `python-passed.yml` workflow, where when the `DateAdded` key gets added to a plugin, a notification is sent to discord stating that a new plugin has been uploaded. I tried to keep the embed similar to the one used for updates, but I made a couple of changes.
1. Added requirements to the `update-tested.py` script and `python-passed.yml` workflow
2. added a `release_hook` function based on `update_hook` to `discord.py`
3. have `update-tested.py` execute `release_hook` for new releases
4. Added webhook_url to `update-tested.py` via a CLI argument 
5. I also fixed a couple of typehints so that my typechecker would stop yelling at me

add plugin release webhook notification

---

ci/src/updater.py

In the changes introduced in #463, a `ValueError` is raised when the regex match the download url. However in the error message, `match` is spelled as `mach`

Fix misspelling of match in regex download url error

---

plugins/Hoarder-cf3dd749-166c-4cbe-8e85-d8d3f2057119.json

Adds FlowLauncher plugin for searching for bookmarks on an Hoarder instance.
For more information on Hoarder: please visit https://hoarder.app/

New plugin: Hoarder

---

plugins/MarkdownTodo-dbe2ddb788c046599a627db1c3ab99af.json

Added a plugin to change todos of markdown files.

New plugin: MarkdownTodo

---

.github/workflows/website-deploy.yml

Deploy website when the plugins.json file is modified on a commit push, this will cover new and updated plugins to the repo. 
For https://github.com/Flow-Launcher/flow-launcher.github.io/pull/45

Add Website deploy on plugins.json modified

---

plugins/SVGl Plugin-AAA4B665C94142F89B7D3DDCEA5E91CF.json

SVGl is just a wrapper around the svgl api , which is used already by power toys run and ray cast
https://github.com/pheralb/svgl
https://svgl.app

Add SVGL to the Plugin manifest

---

ci/src/_utils.py
ci/src/updater.py
ci/src/validator.py

I've noticed quite a few plugin submissions with the download url set to the releases page of their github repo, so this PR simply adds a test to `validator.py` that validates the download url using the download url regex introduced in #462.

Validate download url in `validator.py`

---

plugins/CHZZK-517b8920fe5647e284c29089749ab69b.json

**New Plugin: CHZZK**
Hi there!
This PR adds a new plugin for CHZZK (https://chzzk.naver.com/), a popular video streaming platform in South Korea.
This plugin allows users to conveniently search for channels and livestreams on CHZZK using its official open API, right from the Flow Launcher.
**Key Features**
- **Search Live Streams**: Quickly find and open ongoing livestreams.
- **Search Channels**: Look up your favorite streamers' channels.
- **Secure API Usage**: To protect the necessary API credentials (`Client ID` and `Client Secret`), this plugin utilizes a self-hostable reverse proxy built with Cloudflare Workers. The source code for this proxy is included within this repository, ensuring transparency and security for users.
I believe this plugin will be a great addition for many …

New Plugin: CHZZK

---

README.md

Update README with MinimumAppVersion property

Update README with MinimumAppVersion property

---

plugins/Dialog Jump Files-09f22573-52b9-433b-832e-450e2f91093b.json

Use [Files](https://github.com/files-community/Files) as third-party explorer for dialog jump feature in Flow Launcher
Ported from: [Listary.FileAppPlugin.Files](https://github.com/files-community/Listary.FileAppPlugin.Files)
Tested with Files v4.0.0 and Flow v2.0.0

Add Dialog Jump Files plugin
